name: caramel_cafe_bakery
description: A Flutter app for Caramel Cafe & Bakery
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  getwidget: ^7.0.0
  device_info_plus: ^12.1.0
  webview_flutter: ^4.13.0
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/images/profile.jpg
